x = 0;
try {
  throw 1;
} catch (x)
assert(x == 1);
